#!/usr/bin/env node
// Ground Zero static-site build.
// Reads the canonical seed (data/*.json), enriches it once, and emits:
//   public/                 — the deployable static site (pages + assets + /data snapshots)
//   migrations/001_seed.sql — the optional Cloudflare D1 seed (same data)
// The /api/* Pages Functions reuse lib/enrich.mjs, so there is one source of truth.

import { readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { enrichFilms, enrichOperations, computeStats } from '../lib/enrich.mjs';
import * as T from './templates.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC = join(ROOT, 'public');

const readJSON = async (p) => JSON.parse(await readFile(join(ROOT, p), 'utf8'));
async function write(rel, content) {
  const full = join(PUBLIC, rel);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, content);
}

function sqlStr(v) {
  if (v == null) return 'NULL';
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
}

function buildSeedSQL(operations, films) {
  const lines = [];
  lines.push('-- Ground Zero — D1 seed. Generated by scripts/build.mjs; do not edit by hand.');
  lines.push('-- Optional: the static site does not require D1. Run with:');
  lines.push('--   npx wrangler d1 execute ground-zero --local --file=migrations/001_seed.sql');
  lines.push('');
  lines.push('DROP TABLE IF EXISTS films;');
  lines.push('DROP TABLE IF EXISTS operations;');
  lines.push(`
CREATE TABLE operations (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  year INTEGER,
  country TEXT,
  location_name TEXT,
  latitude REAL,
  longitude REAL,
  total_tests INTEGER,
  max_yield_kt REAL,
  purpose TEXT,
  description TEXT,
  slug TEXT
);`);
  lines.push(`
CREATE TABLE films (
  id TEXT PRIMARY KEY,
  operation_id TEXT REFERENCES operations(id),
  title TEXT NOT NULL,
  ia_identifier TEXT,
  ia_url TEXT,
  yield_kt REAL,
  test_name TEXT,
  test_date TEXT,
  location TEXT,
  creator TEXT,
  downloads INTEGER,
  description TEXT,
  aftermath TEXT,
  weapon TEXT,
  thumbnail_url TEXT,
  slug TEXT
);`);
  lines.push('');
  const opCols = ['id','name','year','country','location_name','latitude','longitude','total_tests','max_yield_kt','purpose','description','slug'];
  for (const o of operations) {
    lines.push(`INSERT INTO operations (${opCols.join(', ')}) VALUES (${opCols.map((c) => sqlStr(o[c])).join(', ')});`);
  }
  lines.push('');
  const filmCols = ['id','operation_id','title','ia_identifier','ia_url','yield_kt','test_name','test_date','location','creator','downloads','description','aftermath','weapon','thumbnail_url','slug'];
  for (const f of films) {
    lines.push(`INSERT INTO films (${filmCols.join(', ')}) VALUES (${filmCols.map((c) => sqlStr(f[c])).join(', ')});`);
  }
  lines.push('');
  return lines.join('\n');
}

const FAVICON = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
<rect width="64" height="64" fill="#0a0a0a"/>
<circle cx="32" cy="32" r="20" fill="none" stroke="#ffb000" stroke-width="2.5"/>
<circle cx="32" cy="32" r="6" fill="#ff6600"/>
<line x1="32" y1="2" x2="32" y2="62" stroke="#332200" stroke-width="1"/>
<line x1="2" y1="32" x2="62" y2="32" stroke="#332200" stroke-width="1"/>
</svg>`;

function ogDefault(stats) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
<rect width="1200" height="630" fill="#0a0a0a"/>
<circle cx="600" cy="315" r="240" fill="none" stroke="#1c1505" stroke-width="2"/>
<circle cx="600" cy="315" r="160" fill="none" stroke="#241b06" stroke-width="2"/>
<circle cx="600" cy="315" r="80" fill="none" stroke="#ff6600" stroke-width="2" opacity="0.5"/>
<text x="80" y="150" fill="#ffb000" font-family="monospace" font-size="84" font-weight="bold" letter-spacing="14">GROUND ZERO</text>
<text x="84" y="205" fill="#cc8800" font-family="monospace" font-size="30" letter-spacing="8">ATMOSPHERIC NUCLEAR TEST FILM ARCHIVE</text>
<text x="84" y="520" fill="#7a5a14" font-family="monospace" font-size="28">${stats.operation_count} operations · ${stats.film_count} films · ${stats.year_min}–${stats.year_max}</text>
</svg>`;
}

async function main() {
  const t0 = Date.now();
  await rm(PUBLIC, { recursive: true, force: true });
  await mkdir(PUBLIC, { recursive: true });

  const rawOps = await readJSON('data/operations.json');
  const rawFilms = await readJSON('data/films.json');

  const operations = enrichOperations(rawOps, rawFilms);
  const films = enrichFilms(rawFilms, rawOps);
  const stats = computeStats(operations, films);

  // 1. Static assets (css, js).
  await cp(join(ROOT, 'src/static'), PUBLIC, { recursive: true });

  // 2. Data snapshots consumed by the client (and as API fallback).
  await write('data/operations.json', JSON.stringify(operations));
  await write('data/films.json', JSON.stringify(films));
  await write('data/stats.json', JSON.stringify(stats));

  // 3. Top-level pages.
  const featured = [...films].sort((a, b) => (b.downloads || 0) - (a.downloads || 0))[0];
  await write('index.html', T.homePage({ stats, featured, operations }));
  await write('operations/index.html', T.operationsPage());
  await write('films/index.html', T.filmsPage());
  await write('map/index.html', T.mapPage());
  await write('timeline/index.html', T.timelinePage());
  await write('about/index.html', T.aboutPage(stats));
  await write('random/index.html', T.randomPage(films.map((f) => f.slug)));
  await write('404.html', T.notFoundPage());

  // 4. Detail pages (clean URLs, full meta — real SEO without a runtime DB).
  for (const f of films) {
    const related = films.filter((r) => r.operation_id && r.operation_id === f.operation_id && r.id !== f.id).slice(0, 6);
    await write(`films/${f.slug}/index.html`, T.filmPage(f, related));
  }
  for (const o of operations) {
    const opFilms = films.filter((f) => f.operation_id === o.id);
    await write(`operations/${o.slug}/index.html`, T.operationDetailPage(o, opFilms));
  }

  // 5. Icons / OG / crawl files.
  await write('favicon.svg', FAVICON);
  await write('og-default.svg', ogDefault(stats));
  await write('robots.txt', `User-agent: *\nAllow: /\nSitemap: ${T.SITE.url}/sitemap.xml\n`);

  const urls = [
    '/', '/operations/', '/films/', '/map/', '/timeline/', '/about/',
    ...operations.map((o) => `/operations/${o.slug}/`),
    ...films.map((f) => `/films/${f.slug}/`),
  ];
  await write('sitemap.xml',
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    urls.map((u) => `  <url><loc>${T.SITE.url}${u}</loc></url>`).join('\n') +
    `\n</urlset>\n`);

  // Long-cache the immutable data snapshots and assets.
  await write('_headers',
    `/data/*\n  Cache-Control: public, max-age=3600\n/css/*\n  Cache-Control: public, max-age=86400\n/js/*\n  Cache-Control: public, max-age=86400\n`);

  // 6. Optional D1 seed (same canonical data).
  await mkdir(join(ROOT, 'migrations'), { recursive: true });
  await writeFile(join(ROOT, 'migrations/001_seed.sql'), buildSeedSQL(operations, films));

  console.log(`✓ Built ${operations.length} operations, ${films.length} films, ${urls.length} pages in ${Date.now() - t0}ms`);
}

main().catch((e) => { console.error(e); process.exit(1); });
